[en]
title = "Issam Alzinati"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

# [ar]
# title = "فلان الفلاني"
# description = "أنا أعمل كمطور ويب في شركة س"
# contentDir = "content/arabic" 
# weight = 2
# LanguageDirection = "rtl" 
# LanguageName = "AR"
